services:
  - type: web
    name: dash-bible-miracles
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server  # Atualize para app:server
    envVars:
      - key: PORT
        value: 8000
    plan: free
